title: "Antonis Mavritsakis â€“ Data Science Portfolio"
layout: single
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

minimal_mistakes_skin: "dark"

custom_css:
  - /assets/css/custom.css
